name: Ottimizza e Pubblica Mappa GPX

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ricalcola percorsi.geojson
        run: python elabora_tracce.py

      - name: Commit e Push del percorsi.geojson
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Ricalcola percorsi.geojson con filtri altimetrici"
          file_pattern: "percorsi.geojson"

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v5

      - name: Carica Artefatto Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
